domains:
  api: http://localhost:9000
  front: http://localhost:8080

db:
  host: localhost
  database: spotimoods
  user: root
  pass: dev
  verbose: true

web:
  port: 9000

app:
  secret: secret123
