port: 9000

domains:
  api: http://localhost:9000
  front: http://localhost:8080

db:
  uri: "root:dev@(localhost)/spotimoods?charset=utf8&parseTime=True&loc=Local"
  verbose: true

rabbit:
  uri: "amqp://guest:guest@localhost:5672/"

spotify:
  client_id: ""
  client_secret: ""
  scope: "user-read-email user-top-read user-read-currently-playing user-read-recently-played playlist-modify-public"

app:
  secret: secret123
