domains:
  api: http://localhost:9000
  front: http://localhost:8080

db:
  host: localhost
  database: spotimoods
  user: root
  pass: dev
  verbose: true

rabbit:
  uri: "amqp://guest:guest@localhost:5672/"

web:
  port: 9000

spotify:
  client_id: ""
  client_secret: ""
  scope: "user-read-email user-top-read user-read-currently-playing user-read-recently-played playlist-modify-public"

app:
  secret: secret123
