port: 9000

domains:
  api: http://localhost:9000
  front: http://localhost:3000

database:
  url: "root:dev@(localhost)/spotimoods?charset=utf8&parseTime=True&loc=Local"
  verbose: true

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"

redis:
  url: "localhost:6379"

spotify:
  client_id: ""
  client_secret: ""
  scope: "user-read-email user-top-read user-read-currently-playing user-read-recently-played playlist-modify-public"

app:
  secret: secret123
