version: '2'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: spotimoods
      MYSQL_ROOT_PASSWORD: dev
    ports:
      - 3306:3306

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
