version: '2'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: spotimoods
      MYSQL_ROOT_PASSWORD: dev
    ports:
      - 3306:3306

  nats:
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222
